### ISSUE TITLE
Change `FieldError` response's `field` value from `"UEN Number"` to `"uen"`

### ISSUE THREAD

**Issue by sheimoria** [vigneshsankariyer1234567890/ghn#21]
`createCharity: {errors: [{field: "UEN Number", message: "A charity with this UEN Number already exists."...`
Frontend input names are aligned with schema field names. In the case of UEN, the schema field name for it is `"uen"`. However, `FieldError`s from incorrect UEN inputs are returning `"UEN Number"` in their `field` field i.e. different naming, so errors are not getting displayed.

**Comment by vigneshsankariyer1234567890** [comment]
resolved, to be tested and verified
